services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
      - ./data:/app/../data
    environment:
      - GIN_MODE=debug
      - DB_PATH=./satdump.db

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
