name: development-sathub
services:
  backend:
    build: ./backend
    ports:
      - "4001:4001"
    volumes:
      - ./backend:/app
    environment:
      - GIN_MODE=debug
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=sathub
      - DB_PASSWORD=sathub_password
      - DB_NAME=sathub
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sathub
      - POSTGRES_PASSWORD=sathub_password
      - POSTGRES_DB=sathub
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  mailpit:
    image: axllent/mailpit
    ports:
      - "8025:8025"
      - "1025:1025"
    volumes:
      - mailpit_data:/data

volumes:
  postgres_data:
  mailpit_data:
